services:
- key: email
  label: Email
  notes: 'Account: andy.kaminski@krealtyllc.org'
- key: epic_property_management
  label: Epic Property Management
  login_url: https://epicpropertymanagement.managebuilding.com
- key: dfcu_financial_bank
  label: DFCU Financial bank
  login_url: https://dfcufinancial.com
- key: first_federal_loan
  label: First Federal loan
  login_url: https://ffl.bank
- key: shellpoint_mortgage
  label: Shellpoint mortgage
  login_url: https://myaccount.shellpointmtg.com
- key: steadily_insurance
  label: Steadily insurance
  login_url: https://steadily.com
- key: homeserve_sewer_insurance
  label: HomeServe sewer insurance
  login_url: https://homeserveid.homeserve.com
- key: squarespace_domain
  label: Squarespace domain
  login_url: https://account.squarespace.com
- key: google_workspace
  label: Google Workspace
  login_url: https://admin.google.com
